### ISSUE TITLE
Recieve tab not working, Firefox tab crashes after a while

### ISSUE THREAD

**Issue by donovan-ringley** [shobhitaa/Joinmarket-SOB#16]
When I open receive tab, it will never stop spinning,

The request for an address will finish,

![image](https://user-images.githubusercontent.com/91415449/156941780-81357a06-5ed3-4580-8e64-8ddf9ea2828d.png)

Then this pops up:

![image](https://user-images.githubusercontent.com/91415449/156941791-2822a234-dfe8-4eff-acb0-1581a9e23aff.png)

And after a while, tab crashes.

When I do refresh (removing `/receive`, the UI is visible with the address for a second and then it will do redirect.

I have Raspiblitz 1.7.2

**Comment by AdamISZ** [comment]
The repo is maintained at https://github.com/joinmarket-webui/joinmarket-webui ; please open the issue there and close this one.

(We probably need to archive this one)
